@startuml
participant Intereses [
    =Intereses
    ----
    ""capital: int ""
    ""interes: int ""
    ""meses: int ""
]
Intereses --> Resultado: capital*interes*meses/100/12
activate Resultado
@enduml
