@startuml
class Precio {
    - precio: int
    - iva = "1,21"
    - calculo_con_iva()
}
@enduml

@startuml
participant Participant [
    =Title
    ----
    ""SubTitle""
]

participant Bob

Participant -> Bob
@enduml

